name: taste
description: Titik food project
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  dots_indicator: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  get: ^4.6.5
  flutter_vibrate: ^1.3.0
  assorted_layout_widgets: ^9.0.0
  shared_preferences: ^2.2.1
  onesignal_flutter: ^5.0.4
  popover: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons_maker: ^0.10.2 # flutter pub run flutter_launcher_icons_maker:main
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launchIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/banners/
    - assets/categories/
    - assets/dishes/corn_dog/
    - assets/dishes/meat_maffin/
    - assets/dishes/potato_pancakes/
    - assets/dishes/sam_menu/samburger/
    - assets/dishes/sam_menu/samdvish/
    - assets/dishes/sam_menu/slime/
    - assets/dishes/sam_menu/reflony_burger/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/cera pro/Cera Pro Medium.otf
        - asset: assets/fonts/cera pro/Cera Pro Regular Italic.otf
          style: italic
        - asset: assets/fonts/cera pro/Cera Pro Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
